service: uvdsa-announce-bot
provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, "dev"}
  runtime: nsolid
  environment:
    LOG_LEVEL: info
  iamRoleStatements: ${file(./cfn/iamRoleStatements.yml)}
  variableSyntax: "\\${((?!AWS)[ ~:a-zA-Z0-9._@'\",\\-\\/\\(\\)]+?)}"
package:
  individually: true
  include:
    - src/**
  exclude:
    - src/__tests__/**
    - node_modules/aws-sdk/**  # The Lambda execution environment provides the aws-sdk builtin, so exclude it from packaging.
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-nsolid-plugin
functions:
  receive:
    memorySize: 128
    handler: src/receive.default
    events:
      - sns:
          arn: !Ref EmailUploadedTopic
          topicName: uvdsa-announce-bot-receive-${self:provider.stage}

resources:
  - ${file(./cfn/cfnSesProvider.yml)}
  - ${file(./cfn/sesToLambda.yml)}

custom:
  domain: ${self:provider.stage}.uvdsa-announce-bot.bjacobel.com
  webpack:
    packager: "yarn"
    includeModules:
      forceExclude:
        - electron
        - aws-sdk
